name: Node-EL-CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        platform: [windows-latest]
        node-version: [10.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
        npm run dist
      env:
        CI: true
