name: Node-EL-CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        platform: [windows-latest]
        node-version: [10.x]
        
    runs-on: ${{ matrix.platform }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
    - name: npm build
      run: npm run build --if-present
    - name: npm test
      run: npm test
    - name: npm release
      run: npm run dist
      env:
        CI: true
        GH_TOKEN:  ${{ secrets.PAC }}
